version: "3.7"
services:
    api:
        build: ./server/
        command: ./manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000

    db:
        image: postgres
        ports: 
            - 5432:5432
            
    client:
        build: ./client/
        command: npm run serve
        ports: 
            - 8080:8080